name: flutter_weather_app
description: A Flutter Weather App.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  skeletonizer: ^0.8.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
